blueprints/landingpageblueprint.py
from flask import Blueprint, request, render_template, session
import hashlib
import pika
from config import Client
from passlib.hash import sha256_crypt
from flask_mail import Mail, Message
import pyotp, time, threading
from MFA import generate_otp

def producer(message):
    rabbitmq_url = "amqps://bdpjerhx:YWZPuQON6FmFnlkw__aghPSdKEPy16HC@cougar.rmq.cloudamqp.com/bdpjerhx"

    connection_parameters = pika.URLParameters(rabbitmq_url)
    connection = pika.BlockingConnection(connection_parameters)
    channel = connection.channel()
    channel.queue_declare(queue='login')
    channel.basic_publish(exchange='', routing_key='login', body=message)
    connection.close()


def consumer(connection_parameters):
    connection = pika.BlockingConnection(connection_parameters)
    channel = connection.channel()
    channel.queue_declare(queue='login')

    def on_message_received(ch, method, properties, body):
        print("Message:", body)
        # Process the message here
        ch.basic_ack(delivery_tag=method.delivery_tag)  # Acknowledge the message

    channel.basic_consume(queue='login', on_message_callback=on_message_received)
    channel.start_consuming()


def consume_single_message(channel):
    queue_name = 'login'
    method_frame, header_frame, body = channel.basic_get(queue=queue_name)

    if method_frame:
        print("Received message:", body)
        # Process the message here

        # Acknowledge the message
        channel.basic_ack(delivery_tag=method_frame.delivery_tag)
    else:
        print("No message in the queue.")


landingPage_blueprint = Blueprint('landingpage', __name__)


@landingPage_blueprint.route('/SCS', methods=['GET', 'POST'])
def landingpage_route():
    if request.method == "POST":
        name = request.form['username']
        password = request.form['password']
        db_newstudent = Client["studentdata"]
        registered_student = db_newstudent["registeredstudents"]

        def get_student_by_name(name):
            filter = {'name': name}
            result = registered_student.find_one(filter, {'_id': 0})
            return result

        resultname = get_student_by_name(name)

        if resultname:
            stored_password = resultname['password']
            stored_emailid = resultname['emailid']
            sha256_hash = hashlib.sha256()
            sha256_hash.update(password.encode('utf-8'))
            hashed_password = sha256_hash.hexdigest()

            if hashed_password == stored_password:
                from app import app
                mail = Mail(app)
                msg = Message('Here is your Code', sender='tejasjagannatha@gmail.com', recipients=[stored_emailid])
                key_obj, key_val = generate_otp.generate_otp()
                msg.html = render_template('mailingsystem/sendotp.html', code=key_val)
                mail.send(msg)
                session['token'] = key_obj
                valid = 1
                producer(stored_emailid)
                return render_template('mfa_check.html', emailid=stored_emailid, isvalid=valid)
            else:
                valid = 0
                producer(stored_emailid)
                return render_template('mfa_check.html', emailid=None, isvalid=valid)
        else:
            valid = 0
            return render_template('mfa_check.html', emailid=None, isvalid=valid)
    else:
        return render_template('scs.html')


@landingPage_blueprint.route('/resetuser', methods=['POST', 'GET'])
def reset_user():
    if request.method == "POST":
        email = request.form['regid']
        db_newstudent = Client["studentdata"]
        registered_student = db_newstudent["registeredstudents"]

        def get_student_by_email(email):
            filter = {'emailid': email}
            result = registered_student.find_one(filter, {'_id': 0})
            return result

        result = get_student_by_email(email)

        if result:
            session['password'] = result['password']
            session['name'] = result['name']
            return render_template('passwordreset.html', password=result['password'], name=result['name'])
        else:
            return render_template('email_notfound.html')
    else:
        return render_template('resetuser.html')


@landingPage_blueprint.route('/changepassword', methods=['POST', 'GET'])
def change_password():
    if request.method == "POST":
        existing_pass = session.get('password')
        username = session.get('name')
        new_pass = request.form['password']
        db_newstudent = Client["studentdata"]
        registered_student = db_newstudent["registeredstudents"]
        sha256_hash = hashlib.sha256()
        sha256_hash.update(new_pass.encode('utf-8'))
        hashed_password = sha256_hash.hexdigest()
        myquery = {"name": username}
        newvalues = {"$set": {"password": hashed_password}}
        registered_student.update_one(myquery, newvalues)
        return render_template('password_change_successful.html')

templates/add_student.html
<!DOCTYPE html>
<html>
<head>
    <title>SCS - School Collaboration System</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            text-align: center;
        }

        .container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            background-color: #393e46;
            background-image: linear-gradient(135deg, #393e46 0%, #13181b 100%);
        }

        .effect {
            position: relative;
            display: inline-block;
            font-size: 72px;
            color: #ffffff;
            background-color: #00adb5;
            padding: 20px 40px;
            border-radius: 10px;
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3);
            overflow: hidden;
            cursor: pointer;
            transition: transform 0.3s, box-shadow 0.3s;
        }

        .effect:before,
        .effect:after {
            content: '';
            position: absolute;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            z-index: -1;
            background-color: #ffcc00;
            transform: scale(0);
            transition: transform 0.3s;
        }

        .effect:before {
            transform-origin: top left;
        }

        .effect:after {
            transform-origin: bottom right;
        }

        .effect:hover {
            transform: translateY(-5px);
            box-shadow: 0 12px 24px rgba(0, 0, 0, 0.3);
        }

        .effect:hover:before,
        .effect:hover:after {
            transform: scale(1);
        }

        .text {
            font-size: 32px;
            margin-top: 20px;
            color: #ffffff;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
            text-align: center;
        }

        .form-container {
            margin: 0 auto;
            max-width: 400px;
            padding: 40px;
            background-color: #f2f2f2;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            font-weight: bold;
            text-align: left; /* Align form elements to the left */
        }

        .form-container label {
            display: block;
            margin-bottom: 5px;
        }

        .form-container input,
        .form-container select {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .form-container button {
            background-color: #00cc00;
            color: #ffffff;
            font-size: 16px;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .form-container button:hover {
            background-color: #00b300;
        }

    </style>
</head>
<body>

<div class="container">
    <div class="effect">SCS</div>
    <h3 class="text">School Collaboration System</h3>
    <br>
    <br>
    <form class="form-container" action="/register-student" method="post">
        <label for="name"><b>Name</b></label>
        <input type="text" id="name" name="name" placeholder="Enter your name:" required>

        <label for="password"><b>Password</b></label>
        <input type="password" id="password" name="password" placeholder="We suggest using a strong password" required>

        <label for="course"><b>Course</b></label>
        <input type="text" id="course" name="course" placeholder="Enter your course:" required>

        <label for="schoolname"><b>Schoolname</b></label>
        <input type="text" id="schoolname" name="schoolname" placeholder="Enter your schoolname:" required>

        <label for="emailid"><b>Emailid</b></label>
        <input type="text" id="emailid" name="emailid" placeholder="Enter your emailid:" required>

        <label for="mobileno"><b>Mobileno</b></label>
        <input type="number" id="mobileno" name="mobileno" placeholder="Enter your mobileno:" required>

        <label for="dropdown">Select your Gender:</label>
        <select id="dropdown" name="dropdown">
            <option value="male">Male</option>
            <option value="female">Female</option>
            <option value="others">Others/Prefer not to say</option>
        </select>

        <label for="address"><b>Address</b></label>
        <input type="text" id="address" name="address" placeholder="Enter your address:" required>

        <button type="submit">Submit</button>
    </form>

    <br><br><br><br><br><br>

    <!-- Motivational quotes for students -->
    <h2 class="text"><i>"Education is the most powerful weapon which you can use to change the world...!"</i></h2>
</div>

</body>
</html>

templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Student Dashboard</title>
    <style>
        /* Set background color for the whole page */
        body {
            margin: 0;
            padding: 0;
            background-color: #6F42C1; /* Purple color */
            display: flex;
            justify-content: center; /* Center horizontally */
            align-items: center; /* Center vertically */
            height: 100vh;
            color: #fff;
            font-family: Arial, sans-serif;
            text-align: center; /* Center the content inside the body */
            line-height: 1; /* Set line-height to 1 */
        }

        h1 {
            color: #00CCCC;
            font-size: 100px; /* Set the font size of the "Welcome" heading */
            margin: 0; /* Remove any default margin for better centering */
        }

        /* Updated Styles for Buttons in .styled-div */
        .styled-div button {
            display: inline-block;
            margin: 10px;
            padding: 12px 20px;
            background-color: #618685; /* Purple color */
            color: #fff;
            text-decoration: none;
            border-radius: 4px;
            border: 2px solid #fff; /* White border with 2px width */
            transition: background-color 0.3s ease;
            font-weight: bold;
        }

        /* Create the border with the correct color (e.g., light purple) */
        .styled-div::before {
            content: "";
            display: block;
            position: absolute;
            top: -8px;
            left: -8px;
            right: -8px;
            bottom: -8px;
            background-color: #8F57A6; /* Light purple color */
            border-radius: 12px;
            z-index: -1;
        }

        .styled-div a:hover {
            background-color: #6F42C1;
        }

        /* Added style for the <p> tag to make it bold */
        p {
            font-weight: bold;
        }

        /* Added style for the <h2> tag to make it bold */
        h2 {
            font-weight: bold;
        }

        /* Styles for making buttons bold */
        .button-link {
            font-weight: bold;
        }

        .button-link:hover {
            font-weight: bold;
            background-color: #fefbd8;
            color: black;
        }

        .styleborder {
            border: 4px solid black;
        }
    </style>
</head>

<body>
    {% if isvalid == 1 %}
    <h1>Welcome!</h1>
    <br>
    <br>
    <br>
    <br>
    <h2><b>These are the available universities you can select to get access to its resources.</b></h2>
    <form action="/university" method="post">
        <div class="styleborder">
            <div class="styled-div">
                <button class="button-link" name="university" value="ul"><b>Irshad High School</b></button>
                <button class="button-link" name="university" value="dcu"><b>Colaiste Nano Nagle School</b></button>
            </div>
        </div>
    </form>
    {% else %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var userConfirmed = confirm('Code has expired or Invalid Code');
            if (userConfirmed) {
                window.location.href = '{{ url_for('landingpage.landingpage_route') }}';
            }
        });
    </script>
    {% endif %}
</body>
</html>

templates/email_notfound.html
<html>
<head>
    <title>SCS - School Collaboration System</title>
    <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      text-align: center;

    }

    .container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      flex-direction: column;
      background-color: #393e46;
      background-image: linear-gradient(135deg, #393e46 0%, #13181b 100%);
    }

    .effect {
      position: relative;
      display: inline-block;
      font-size: 72px;
      color: #ffffff;
      background-color: #00adb5;
      padding: 20px 40px;
      border-radius: 10px;
      box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3);
      overflow: hidden;
      cursor: pointer;
      transition: transform 0.3s, box-shadow 0.3s;
    }

    .effect:before,
    .effect:after {
      content: '';
      position: absolute;
      width: 100%;
      height: 100%;
      top: 0;
      left: 0;
      z-index: -1;
      background-color: #ffcc00;
      transform: scale(0);
      transition: transform 0.3s;
    }

    .effect:before {
      transform-origin: top left;
    }

    .effect:after {
      transform-origin: bottom right;
    }

    .effect:hover {
      transform: translateY(-5px);
      box-shadow: 0 12px 24px rgba(0, 0, 0, 0.3);
    }

    .effect:hover:before,
    .effect:hover:after {
      transform: scale(1);
    }

    .text {
      font-size: 32px;
      margin-top: 20px;
      color: #ffffff;
      text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
      text-align: center;
    }

 .form-container {
      margin: 0 auto;
      max-width: 400px;
      padding: 40px;
      background-color: #f2f2f2;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      font-weight: bold;
    }

   button:hover {
      background-color: #00cc00;
font-weight: bold;
    }

   .signup:hover{
    background-color: #007bff;
font-weight: bold;
    }

    </style>
</head>
<body>

<div class="container">
    <div class="effect">SCS</div>
    <h3 class="text">School Collaboration System</h3>
    <br>
    <br>
    <div class="form-container" >
        <h3>Email ID is not registered</h3>
        <a href="{{ url_for('landingpage.landingpage_route') }}">Go to Sign in</a>

    </div>

    <br><br><br><br><br><br>

    <!-- Motivational quotes for students -->
    <h2 class="text"><i>"Education is the most powerful weapon which you can use to change the world...!"</i></h2>
</div>

</body>
</html>

templates/mfa_check.html
<html>
<head>
  <title>SCS - School Collaboration System</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      text-align: center;
      background-color: #f2f2f2;
      background-image: linear-gradient(135deg, #393e46 0%, #13181b 100%);
    }

    .container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      flex-direction: column;
    }

    .effect {
      position: relative;
      display: inline-block;
      font-size: 72px;
      color: #ffffff;
      background-color: #00adb5;
      padding: 20px 40px;
      border-radius: 10px;
      box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3);
      overflow: hidden;
      cursor: pointer;
      transition: transform 0.3s, box-shadow 0.3s;
    }

    .effect:before,
    .effect:after {
      content: '';
      position: absolute;
      width: 100%;
      height: 100%;
      top: 0;
      left: 0;
      z-index: -1;
      background-color: #ffcc00;
      transform: scale(0);
      transition: transform 0.3s;
    }

    .effect:before {
      transform-origin: top left;
    }

    .effect:after {
      transform-origin: bottom right;
    }

    .effect:hover {
      transform: translateY(-5px);
      box-shadow: 0 12px 24px rgba(0, 0, 0, 0.3);
    }

    .effect:hover:before,
    .effect:hover:after {
      transform: scale(1);
    }

    .text {
      font-size: 32px;
      margin-top: 20px;
      color: #ffffff;
      text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
      text-align: center;
    }

    .form-container {
      margin: 0 auto;
      max-width: 400px;
      padding: 40px;
      background-color: #f2f2f2;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      font-weight: bold;
      margin-top: 40px;
    }

    .form-container label {
      display: block;
      margin-bottom: 10px;
      color: #333333;
    }

    .form-container input[type="text"] {
      width: 100%;
      padding: 10px;
      margin-bottom: 20px;
      border: 1px solid #cccccc;
      border-radius: 4px;
    }

    .form-container button[type="submit"] {
      width: 100%;
      padding: 10px;
      background-color: #00adb5;
      border: none;
      color: #ffffff;
      font-weight: bold;
      border-radius: 4px;
      cursor: pointer;
      transition: background-color 0.3s;
    }

    .form-container button[type="submit"]:hover {
      background-color: #0093a9;
    }
  </style>
</head>
<body>

<div class="container">
    <div class="effect">SCS</div>
    <h3 class="text">School Collaboration System</h3>
    <br>
    <br>
    <form class="form-container" action="/dashboard" method="post">
        <label for="token"><b>Enter Code sent to your EmailId: {{emailid}} to Login</b></label>
        <input type="text" id="token" name="token" placeholder="Enter Code" required>
        <br>
        <br>
        <button type="submit" name="login">Ok</button>
    </form>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    <!-- Motivational quotes for students -->
    <h2 class="text"><i>"Education is the most powerful weapon which you can use to change the world...!"</i></h2>
</div>

</body>
</html>

templates/password_change_successful.html
<html>
<head>
    <title>SCS - School Collaboration System</title>
    <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      text-align: center;

    }

    .container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      flex-direction: column;
      background-color: #393e46;
      background-image: linear-gradient(135deg, #393e46 0%, #13181b 100%);
    }

    .effect {
      position: relative;
      display: inline-block;
      font-size: 72px;
      color: #ffffff;
      background-color: #00adb5;
      padding: 20px 40px;
      border-radius: 10px;
      box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3);
      overflow: hidden;
      cursor: pointer;
      transition: transform 0.3s, box-shadow 0.3s;
    }

    .effect:before,
    .effect:after {
      content: '';
      position: absolute;
      width: 100%;
      height: 100%;
      top: 0;
      left: 0;
      z-index: -1;
      background-color: #ffcc00;
      transform: scale(0);
      transition: transform 0.3s;
    }

    .effect:before {
      transform-origin: top left;
    }

    .effect:after {
      transform-origin: bottom right;
    }

    .effect:hover {
      transform: translateY(-5px);
      box-shadow: 0 12px 24px rgba(0, 0, 0, 0.3);
    }

    .effect:hover:before,
    .effect:hover:after {
      transform: scale(1);
    }

    .text {
      font-size: 32px;
      margin-top: 20px;
      color: #ffffff;
      text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
      text-align: center;
    }

 .form-container {
      margin: 0 auto;
      max-width: 400px;
      padding: 40px;
      background-color: #f2f2f2;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      font-weight: bold;
    }

   button:hover {
      background-color: #00cc00;
font-weight: bold;
    }

   .signup:hover{
    background-color: #007bff;
font-weight: bold;
    }

    </style>
</head>
<body>

<div class="container">
    <div class="effect">SCS</div>
    <h3 class="text">School Collaboration System</h3>
    <br>
    <br>
    <div class="form-container">
        <h3>Password has been Changed Successfully</h3>
        <a href="{{ url_for('landingpage.landingpage_route') }}">Go to Sign in</a>

    </div>

    <br><br><br><br><br><br>

    <!-- Motivational quotes for students -->
    <h2 class="text"><i>"Education is the most powerful weapon which you can use to change the world...!"</i></h2>
</div>

</body>
</html>

templates/passwordreset.html
<html>
<head>
    <title>SCS - School Collaboration System</title>
    <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      text-align: center;

    }

    .container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      flex-direction: column;
      background-color: #393e46;
      background-image: linear-gradient(135deg, #393e46 0%, #13181b 100%);
    }

    .effect {
      position: relative;
      display: inline-block;
      font-size: 72px;
      color: #ffffff;
      background-color: #00adb5;
      padding: 20px 40px;
      border-radius: 10px;
      box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3);
      overflow: hidden;
      cursor: pointer;
      transition: transform 0.3s, box-shadow 0.3s;
    }

    .effect:before,
    .effect:after {
      content: '';
      position: absolute;
      width: 100%;
      height: 100%;
      top: 0;
      left: 0;
      z-index: -1;
      background-color: #ffcc00;
      transform: scale(0);
      transition: transform 0.3s;
    }

    .effect:before {
      transform-origin: top left;
    }

    .effect:after {
      transform-origin: bottom right;
    }

    .effect:hover {
      transform: translateY(-5px);
      box-shadow: 0 12px 24px rgba(0, 0, 0, 0.3);
    }

    .effect:hover:before,
    .effect:hover:after {
      transform: scale(1);
    }

    .text {
      font-size: 32px;
      margin-top: 20px;
      color: #ffffff;
      text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
      text-align: center;
    }

 .form-container {
      margin: 0 auto;
      max-width: 400px;
      padding: 40px;
      background-color: #f2f2f2;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      font-weight: bold;
    }

   button:hover {
      background-color: #00cc00;
font-weight: bold;
    }

   .signup:hover{
    background-color: #007bff;
font-weight: bold;
    }

    </style>
</head>
<body>

<div class="container">
    <div class="effect">SCS</div>
    <h3 class="text">School Collaboration System</h3>
    <br>
    <br>
    <form class="form-container" action="/changepassword" method="post">
        <label for="password"><b>Enter New Password</b></label>
        <input type="text" id="password" name="password" placeholder="Enter your new password: " required>
        <br>
        <br>
        <button type="submit" name="changepassword">Change Password</button>

    </form>

    <br><br><br><br><br><br>

    <!-- Motivational quotes for students -->
    <h2 class="text"><i>"Education is the most powerful weapon which you can use to change the world...!"</i></h2>
</div>

</body>
</html>

templates/resetuser.html
<html>
<head>
    <title>SCS - School Collaboration System</title>
    <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      text-align: center;

    }

    .container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      flex-direction: column;
      background-color: #393e46;
      background-image: linear-gradient(135deg, #393e46 0%, #13181b 100%);
    }

    .effect {
      position: relative;
      display: inline-block;
      font-size: 72px;
      color: #ffffff;
      background-color: #00adb5;
      padding: 20px 40px;
      border-radius: 10px;
      box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3);
      overflow: hidden;
      cursor: pointer;
      transition: transform 0.3s, box-shadow 0.3s;
    }

    .effect:before,
    .effect:after {
      content: '';
      position: absolute;
      width: 100%;
      height: 100%;
      top: 0;
      left: 0;
      z-index: -1;
      background-color: #ffcc00;
      transform: scale(0);
      transition: transform 0.3s;
    }

    .effect:before {
      transform-origin: top left;
    }

    .effect:after {
      transform-origin: bottom right;
    }

    .effect:hover {
      transform: translateY(-5px);
      box-shadow: 0 12px 24px rgba(0, 0, 0, 0.3);
    }

    .effect:hover:before,
    .effect:hover:after {
      transform: scale(1);
    }

    .text {
      font-size: 32px;
      margin-top: 20px;
      color: #ffffff;
      text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
      text-align: center;
    }

 .form-container {
      margin: 0 auto;
      max-width: 400px;
      padding: 40px;
      background-color: #f2f2f2;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      font-weight: bold;
    }

   button:hover {
      background-color: #00cc00;
font-weight: bold;
    }

   .signup:hover{
    background-color: #007bff;
font-weight: bold;
    }

    </style>
</head>
<body>

<div class="container">
    <div class="effect">SCS</div>
    <h3 class="text">School Collaboration System</h3>
    <br>
    <br>
    <form class="form-container" action="/resetuser" method="post">
        <label for="regid"><b>EmailID</b></label>
        <input type="text" id="regid" name="regid" placeholder="Enter your registered emailid" required>
        <br>
        <br>
        <button type="submit" name="forgot">Forgot user/password</button>

    </form>

    <br><br><br><br><br><br>

    <!-- Motivational quotes for students -->
    <h2 class="text"><i>"Education is the most powerful weapon which you can use to change the world...!"</i></h2>
</div>

</body>
</html>

templates/scs.html
<html>
<head>
    <title>SCS - School Collaboration System</title>
    <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      text-align: center;

    }

    .container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      flex-direction: column;
      background-color: #393e46;
      background-image: linear-gradient(135deg, #393e46 0%, #13181b 100%);
    }

    .effect {
      position: relative;
      display: inline-block;
      font-size: 72px;
      color: #ffffff;
      background-color: #00adb5;
      padding: 20px 40px;
      border-radius: 10px;
      box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3);
      overflow: hidden;
      cursor: pointer;
      transition: transform 0.3s, box-shadow 0.3s;
    }

    .effect:before,
    .effect:after {
      content: '';
      position: absolute;
      width: 100%;
      height: 100%;
      top: 0;
      left: 0;
      z-index: -1;
      background-color: #ffcc00;
      transform: scale(0);
      transition: transform 0.3s;
    }

    .effect:before {
      transform-origin: top left;
    }

    .effect:after {
      transform-origin: bottom right;
    }

    .effect:hover {
      transform: translateY(-5px);
      box-shadow: 0 12px 24px rgba(0, 0, 0, 0.3);
    }

    .effect:hover:before,
    .effect:hover:after {
      transform: scale(1);
    }

    .text {
      font-size: 32px;
      margin-top: 20px;
      color: #ffffff;
      text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
      text-align: center;
    }

 .form-container {
      margin: 0 auto;
      max-width: 400px;
      padding: 40px;
      background-color: #f2f2f2;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      font-weight: bold;
    }

   button:hover {
      background-color: #00cc00;
font-weight: bold;
    }

   .signup:hover{
    background-color: #007bff;
font-weight: bold;
    }

    .forgotdetails:hover{
    background-color: #FF0000;
font-weight: bold;
    }
    </style>
</head>
<body>
<div class="container">
    <div class="effect">SCS</div>
    <h3 class="text">School Collaboration System</h3>
    <br>
    <br>
    <form class="form-container" action="/SCS" method="post">
        <label for="username"><b>Username</b></label>
        <input type="text" id="username" name="username" placeholder="Enter your username" required>
        <br>
        <br>
        <label for="password"><b>Password</b></label>
        <input type="password" id="password" name="password" placeholder="Enter your password" required>
        <br>
        <br>
        <button type="submit" name="login">Login</button>

        <input type="button" class="signup" value="SignUp" onclick="window.location.href='/register-student'">
        <!-- Move the "Forgot Details" button here -->
        <button class="forgotdetails" onclick="window.location.href='/resetuser'">Forgot Details</button>
    </form>

    <br><br><br><br><br><br>

    <!-- Motivational quotes for students -->
    <h2 class="text"><i>"Education is the most powerful weapon which you can use to change the world...!"</i></h2>
</div>

</body>
</html>